language: go
go:
- 1.7
script: make test build
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: kHKmiVuAQbqWxO/2+f1tljV+iGumXeF37WaV3wYkG+7zhIt7kySeMIOhsQV+Wkf2ma6gs+jZT5M6H5bHiyAo82byfk7tIGT59IHRY7FysqjRUu2iCQooQS+gIM1pIEQmLIAnyp9nSScUGERAGhRUdXfpGGJwz5/c7rB23LsIRs4ZejTT3nKsK/y7gWZfM4bxqS6bYBkToZ+Y4h7hKow35vjry9mXjyLuXv8DEXAHcVBW1lXz4jLIXskhq7J2BtBOMkfdPoYrUMC+rdnlM4p0XGA2E5C/XYmWH9MTEe+cwj+pB0i/CiUTxg4xkV2Oc5qMI6RmiyI0oaz5YQJjO611oOMKFAmOqLKauNFlEcLM8o5fcDMOoDwrgZSkWdrDlENOqTlHOJF544b0jRD3buQX9Ywy9Y7CHVW8o3cO+rtQat68YVFpOOYJ37vGJ9QlMYI+d0j4EgZsbMss+GVqy5sDKD3SeDCWBz6m5pjJDcVmIP+HAD4qqfS7Ns7/Syy07cJPLDa/4VKOpNnj8tXeFdRhCEwSO2VuM/x7Jvt7JulJOWrK2DqFFq4G9mNV2a/MAi2ZXYsIiwYoRRAyePuSq87Emk19cr9t8lJOyRXDMI0/thVMD1wiUV2UoEyk9Gcx1lklOog3KMuM69ZnMj7OCLxZWp+rAWmgdIfPuH2o8lW8mUU=
  file: check-ssl
  on:
    tags: true
notifications:
  slack:
    secure: CyfbieXN6l/6pdutRh03mck+RVzu39ykBEX3+TXPD7aGMKflukgFUIAMgeP7PHzgnl+S/8ECodLMow8/uHtTJl5s1xRfbSBJOn3VWlw6NCaO2aqAAwX72cZMvUXXTPXSJbDSXuDPPAHp/qQXXw4TzMl+BWnCrRBDXp6dH67Ul+5zUuvMrFd/gsdZL6Y1pa4z06Rg5ojn6so+6nQYgTT6txiSREZ8c8C57c7wZ3CBapeWwMonjI8wrz8BgnOAIqHBXPetRqgPHpavBtniDClId1Qh9Kdy+JjWvMEQEiHL29A0NDvuYmSNvi8BawF4vy+mBUsSzFhiu2bCbHlSqDlo2XHijGeaopvzdu5ih6Nq71MWi+ANaLBRx4pTGXFxiMUiGgLl+/ts+u+LuKA5dKN3hF0FaP/fBnAJe2v6tDhkFxQHCWTNEp68nJ+ADovu3yItngP14lt/qDdNTqATRKX4G4Fl7UECD10J2Wf7PJjw3tnSKLo3fGOUQzlhzgdLf1MVNvYgzkk13yf25VI9h9+QFhbVBqYYQ1r8HsKbhNLY80HebSTdiLB08qpCk+BDJ+39yTZVEBhIeJP8wV5AUAlxEe0rB4yBp2Jo1A5LjR7KPtJ4rVImwqfiUQmlPeY0d8MH8q6YR/xXKVU6C+7tbzdaRqYl7qIB7EvQ+jO7Px0T1IQ=


